# Generated by Django 2.1.7 on 2019-04-14 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='login',
        ),
        migrations.AddField(
            model_name='profile',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asker.Profile'),
        ),
    ]
