# Generated by Django 2.1.7 on 2019-04-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0002_auto_20190414_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.AddField(
            model_name='like',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asker.Profile'),
        ),
        migrations.AddField(
            model_name='like',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asker.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asker.Profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asker.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='asker.Tag'),
        ),
    ]
