# Generated by Django 2.1.7 on 2019-04-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0003_auto_20190416_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tags',
            field=models.ManyToManyField(to='asker.Tag'),
        ),
    ]
