# Generated by Django 2.1.7 on 2019-04-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0004_answer_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tags',
        ),
    ]
